services:
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: x-twitter-sim
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./twitter-api-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d x-twitter-sim"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./twitter-api-service
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/v1/agents || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
